esphome:
  name: boiler-controller
  on_boot:
    - priority: -100
      then:
        - light.turn_on:
            id: boiler_status_leds
            brightness: 50%
            effect: "Boiler Status"

wifi:
  id: wifi_component
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:
  id: api_server

ota:
  - platform: esphome
    password: !secret ota_password

web_server:
  port: 80

esp32:
  variant: ESP32C3
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

one_wire:
  - platform: gpio
    pin: GPIO0         # one wire pin
    id: one_wire_bus

sensor:
  - platform: dallas_temp
    one_wire_id: one_wire_bus
    name: "Boiler Box Temperature"
    id: boiler_box_temp
    address:  0x4b3c01b556779328
    update_interval: 5s
  - platform: dallas_temp
    one_wire_id: one_wire_bus
    name: "Boiler Top Temperature"
    id: boiler_temp_top
    address:  0x9050d7d4458bc828
    update_interval: 5s

external_components:
  - source: ./external

number:
  - platform: template
    name: "Power percent"
    id: power_percent
    min_value: 0
    max_value: 100
    step: .1
    optimistic: true

select:
  - platform: template
    name: "Power mode"
    id: power_mode
    optimistic: true
    options:
      - "Off"
      - "On"
      - "Auto"
      - "Manual"

my_component:
  id: boiler_controller
  power: power_percent
  mode: power_mode
  clock: GPIO3
  trigger: GPIO4

light: 
  # todo Addressable Lambda Effect
  - platform: esp32_rmt_led_strip
    pin: GPIO1
    num_leds: 2
    name: "Boiler staus Leds"
    id: boiler_status_leds
    chipset: WS2812
    rgb_order: GRB
    rmt_channel: 1
    effects:
    # Example 1: Show WiFi and API connection status
    - addressable_lambda:
        name: "Boiler Status"
        update_interval: 500ms
        lambda: |-
          // LED 0: WiFi status
          if (id(wifi_component).is_connected()) {
            it[0] = Color(0, 255, 0);  // Green = connected
          } else {
            it[0] = Color(255, 0, 0);  // Red = disconnected
          }
          
          // LED 1: boiler mode
          std::string m = id(power_mode).state;
          if (m=="Off") {
            it[1] = Color(255, 0, 0);
          } 
          else if (m=="On") {
            it[1] = Color(0, 255, 0);
          } 
          else if (m=="Manual") {
            it[1] = Color(255, 255, 0);
          }           
          else if (m=="Auto") {
            it[1] = Color(0, 0, 255);
          } 


# LCD bus I2C
i2c:
  sda: GPIO5
  scl: GPIO6
  scan: true
  id: bus_a
  frequency: 800kHz

# Font
font:
  - file: "gfonts://Roboto"
    id: my_font
    size: 12
  - file: fonts/JetBrainsMono-Light.ttf
    id: nerd
    size: 16

# Display settings
display:
  - platform: ssd1306_i2c
    model: "sh1106 128x64"
    address: 0x3C
    id: my_display
    update_interval: 5s
    rotation: 0
    offset_y: 0
    offset_x: 0
    lambda: |-
      it.fill(Color::BLACK);
      it.print(27, 20, id(my_font), "ABCDEFG");
      it.printf(27, 40, id(nerd), "B:%.1f C", id(boiler_box_temp).state);
      //it.line(27, 20, 127+27, 63+20, Color::WHITE);
      //it.line(127, 0, 0, 63, Color::WHITE);